baseURL: http://{BASE_URL}/
languageCode: "en-us"
title: "Data STAGE"
sections: ["About", "Products", "Contact"]
permalinks:
  sections: :title
params:
  logo:
    src: /img/stage-logo.svg
    alt: Data STAGE Logo
  productDropdownText: "Select your data set"
