baseURL: "http://example.org"
languageCode: "en-us"
title: "Data STAGE"
sections: ["About", "Tools", "Contact"]
permalinks:
  sections: \#:title
params:
  logo:
    src: /img/datastage-logo.svg
    alt: Data STAGE Logo
  toolDropdownText: "Select your data set"
